'use client';
import { useEffect, useState } from 'react';
import ReactCrop, { Crop, PixelCrop } from 'react-image-crop';
import 'react-image-crop/dist/ReactCrop.css';
import { FlipHorizontal, FlipVertical, RotateCcw, RotateCw, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
type Ratio = 'original' | 'square' | 'landscape' | 'portrait' | 'wide';
const ratios: Record<Exclude<Ratio, 'original'>, number> = { square: 1, landscape: 4 / 3, portrait: 3 / 4, wide: 16 / 9 };
async function exportCrop(url: string, crop: PixelCrop, rotation: number, flipX: boolean, flipY: boolean) { const image = new Image(); image.src = url; await new Promise<void>((resolve, reject) => { image.onload = () => resolve(); image.onerror = () => reject(new Error('Image could not be loaded.')); }); const sx = image.naturalWidth / image.width; const sy = image.naturalHeight / image.height; const canvas = document.createElement('canvas'); canvas.width = Math.round(crop.width * sx); canvas.height = Math.round(crop.height * sy); const context = canvas.getContext('2d'); if (!context) throw new Error('Canvas unavailable.'); context.translate(canvas.width / 2, canvas.height / 2); context.rotate(rotation * Math.PI / 180); context.scale(flipX ? -1 : 1, flipY ? -1 : 1); context.drawImage(image, -crop.x * sx - canvas.width / 2, -crop.y * sy - canvas.height / 2, image.naturalWidth, image.naturalHeight); const blob = await new Promise<Blob | null>(resolve => canvas.toBlob(resolve, 'image/jpeg', 0.92)); if (!blob) throw new Error('Could not export image.'); return new File([blob], 'edited-product-image.jpg', { type: 'image/jpeg' }); }
export function ImageEditorDialog({ imageUrl, productName, saving, onClose, onSave }: { imageUrl: string; productName: string; saving?: boolean; onClose: () => void; onSave: (file: File) => void }) {
  const [sourceUrl, setSourceUrl] = useState(imageUrl); const [ratio, setRatio] = useState<Ratio>('original'); const [aspect, setAspect] = useState<number>(); const [crop, setCrop] = useState<Crop>({ unit: '%', x: 0, y: 0, width: 100, height: 100 }); const [pixelCrop, setPixelCrop] = useState<PixelCrop>(); const [zoom, setZoom] = useState(1); const [rotation, setRotation] = useState(0); const [flipX, setFlipX] = useState(false); const [flipY, setFlipY] = useState(false);
  useEffect(() => { let objectUrl = ''; void fetch(imageUrl).then(response => response.blob()).then(blob => { objectUrl = URL.createObjectURL(blob); setSourceUrl(objectUrl); }).catch(() => setSourceUrl(imageUrl)); return () => { if (objectUrl) URL.revokeObjectURL(objectUrl); }; }, [imageUrl]);
  const changeRatio = (value: Ratio) => { const nextAspect = value === 'original' ? undefined : ratios[value]; setRatio(value); setAspect(nextAspect); if (!nextAspect) { setCrop({ unit: '%', x: 0, y: 0, width: 100, height: 100 }); return; } const width = nextAspect >= 1 ? 80 : Math.round(80 * nextAspect); const height = nextAspect >= 1 ? Math.round(80 / nextAspect) : 80; setCrop({ unit: '%', x: (100 - width) / 2, y: (100 - height) / 2, width, height }); };
  const changeZoom = (value: number) => { setZoom(value); const width = Math.max(10, Math.min(80, 80 / value)); const height = aspect ? Math.min(80, width / aspect) : width; setCrop(current => ({ ...current, x: (100 - width) / 2, y: (100 - height) / 2, width, height })); };
  return <div className="fixed inset-0 z-[70] flex items-start justify-center overflow-y-auto bg-black/75 p-4 sm:p-6"><Card className="my-auto max-h-[calc(100vh-2rem)] w-full max-w-5xl overflow-y-auto"><CardHeader className="sticky top-0 z-10 flex flex-row items-center justify-between border-b bg-background"><div><CardTitle>Edit image · {productName}</CardTitle><p className="mt-1 text-sm text-muted-foreground">Drag or resize the crop box, then pan, rotate, flip, and zoom.</p></div><Button variant="ghost" size="icon" onClick={onClose}><X /></Button></CardHeader><CardContent className="space-y-4"><div className="flex min-h-64 max-h-[min(58vh,620px)] items-center justify-center overflow-auto rounded-xl bg-neutral-950 p-4"><ReactCrop crop={crop} aspect={aspect} onChange={(_, percentCrop) => setCrop(percentCrop)} onComplete={pixels => setPixelCrop(pixels)}><img src={sourceUrl} alt={`${productName} preview`} className="max-h-[min(52vh,560px)] max-w-full object-contain" style={{ transform: `scaleX(${flipX ? -1 : 1}) scaleY(${flipY ? -1 : 1}) rotate(${rotation}deg)` }} /></ReactCrop></div><div className="flex flex-wrap gap-2"><span className="self-center text-sm font-medium">Crop box</span>{([['original', 'Original'], ['square', '1:1'], ['landscape', '4:3'], ['portrait', '3:4'], ['wide', '16:9']] as const).map(([value, label]) => <Button key={value} size="sm" variant={ratio === value ? 'default' : 'outline'} onClick={() => changeRatio(value)}>{label}</Button>)}</div><div className="flex flex-wrap items-center gap-2"><Button size="sm" variant="outline" onClick={() => setRotation(value => value - 90)}><RotateCcw className="mr-1 h-4 w-4" /> Rotate left</Button><Button size="sm" variant="outline" onClick={() => setRotation(value => value + 90)}><RotateCw className="mr-1 h-4 w-4" /> Rotate right</Button><Button size="sm" variant="outline" onClick={() => setFlipX(value => !value)}><FlipHorizontal className="mr-1 h-4 w-4" /> Flip horizontal</Button><Button size="sm" variant="outline" onClick={() => setFlipY(value => !value)}><FlipVertical className="mr-1 h-4 w-4" /> Flip vertical</Button><label className="ml-auto flex items-center gap-2 text-sm">Zoom <input type="range" min="1" max="3" step="0.05" value={zoom} onChange={event => changeZoom(Number(event.target.value))} /></label></div><div className="flex justify-end gap-2"><Button variant="outline" onClick={onClose}>Cancel</Button><Button disabled={!pixelCrop || saving} onClick={() => pixelCrop && void exportCrop(sourceUrl, pixelCrop, rotation, flipX, flipY).then(onSave)}>{saving ? 'Saving...' : 'Save edited image'}</Button></div></CardContent></Card></div>;
}
