/**
 * Coded by Harith
 * Kampungcetak ®
 */
import { Router } from "express";
import authController from "../controllers/auth.controller";
import authMiddilware, { authorizeRoles } from "../middlewares/auth.middileware";

const router = Router();

router.post("/login", authController.login.bind(authController));

router.post("/register", authController.register.bind(authController));

router.post("/refresh", authController.refresh.bind(authController));

// Magic login links: generated by sysadmin/boss, redeemed without a password.
router.post("/magic-login", authController.magicLogin.bind(authController));

router.post("/magic-link", authMiddilware, authorizeRoles("sysadmin", "boss"), authController.generateMagicLink.bind(authController));

export default router;

